# Generated by Django 4.1.4 on 2023-02-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='school',
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='school',
            field=models.ManyToManyField(to='home.school'),
        ),
    ]
