# Generated by Django 4.1.4 on 2023-02-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_school_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
    ]
